number1= input('Enter number 1')
number2= input('Enter number 2')
print(number1,number2)
sum=int(number1)+int(number2)
print(sum)
difference=int(number1)-int(number2)
print(difference)
multiply=int(number1)*int(number2)
print(multiply)
division=int(number1)/int(number2)
print(division)
print(sum,difference,multiply,division)
number3=input('Enter number 3')
print(number1,number2,number3)
sum=int(number1)+int(number2)+int(number3)
print(sum)
difference=int(number1)-int(number2)-int(number3)
print(difference)
multiply=int(number1)*int(number2)*int(number3)
print(multiply)
division=int(number1)/int(number2)/int(number3)
print(division)
import math
print(math.pow(9,3))